configs = {    
    'InvertedPendulum-v4': {
        "PPO": {
            "hyperparameters": {
                "total_timesteps": 100000,
                "algorithm": "PPO",
                "learning_rate": 3e-4,
                "n_steps": 2048,
                "batch_size": 64,
                "n_epochs": 10,
                "gamma": 0.99,
                "gae_lambda": 0.95,
                "clip_range": 0.2,
                "ent_coef": 0.01,
                "vf_coef": 0.5,
                "max_grad_norm": 0.5,
                "log_interval": 10,
                "eval_freq": 2000,
                "save_freq": 10000,
                "Run_name": "PPO_IP"
            },            
        },
        
        "A2C": {
            "hyperparameters": {
                "total_timesteps": 200000,
                "algorithm": "A2C",
                "learning_rate": 3e-4,
                "n_steps": 8,
                "gamma": 0.99,
                "gae_lambda": 0.95,
                "ent_coef": 0.01,
                "vf_coef": 0.5,
                "max_grad_norm": 0.5,
                "normalize_advantage": True,
                "log_interval": 10,
                "eval_freq": 2000,
                "save_freq": 10000,
                "Run_name": "A2C_IP",
                "use_rms_prop": True,
            },            
        },
    },
    
    'HalfCheetah-v4': {
        "PPO": {
            "hyperparameters": {
                'learning_rate': 3e-4,
                'n_steps': 2048,
                'batch_size': 64,
                'n_epochs': 10,
                'gamma': 0.99,
                'gae_lambda': 0.95,
                'clip_range': 0.2,
                'ent_coef': 0.01,
                'vf_coef': 0.5,
                'max_grad_norm': 0.5,
                'total_timesteps': 1000000,
                "log_interval": 10,
                "eval_freq": 10000,
                "save_freq": 50000,
                "Run_name": "PPO_Cheetah",
                "normalize_advantage": True,
            },
        },
        
        "A2C": {
            "hyperparameters": {
            "total_timesteps": 5_000_000,
            "algorithm": "A2C",
            "learning_rate": 5e-4,
            "n_steps": 8,
            "gamma": 0.99,
            "gae_lambda": 1.0,
            "ent_coef": 0.0,
            "vf_coef": 0.25,
            "max_grad_norm": 0.5,
            "normalize_advantage": False,
            "use_rms_prop": True,
            "rms_prop_eps": 1e-5,
            "Run_name": "A2C_Cheetah",
            "policy_kwargs": {
                "net_arch": [128,128],
            }
            },       
        },
    },
    
    'Hopper-v4': {
        "PPO": {
            "hyperparameters": {
                "total_timesteps": 2_000_000,
                "algorithm": "PPO",
                "learning_rate": 3e-4,
                "n_steps": 2048,
                "batch_size": 64,
                "n_epochs": 10,
                "gamma": 0.99,
                "gae_lambda": 0.95,
                "clip_range": 0.2,
                "ent_coef": 0.0,
                "vf_coef": 0.5,
                "max_grad_norm": 0.5,
                "log_interval": 10,
                "eval_freq": 10000,
                "save_freq": 50000,
                "Run_name": "PPO_Hopper",
                "normalize_advantage": True,
                "policy_kwargs": dict(net_arch=[dict(pi=[256, 256], vf=[256, 256])]),
            },            
        },
        
        "A2C": {
            "hyperparameters": {
                "total_timesteps": 2_000_000,
                "algorithm": "A2C",
                "learning_rate": 3e-4,
                "n_steps": 16,
                "gamma": 0.99,
                "gae_lambda": 0.95,
                "ent_coef": 0.0,
                "vf_coef": 0.5,
                "max_grad_norm": 0.5,
                "normalize_advantage": True,
                "log_interval": 10,
                "eval_freq": 10000,
                "save_freq": 50000,
                "Run_name": "A2C_Hopper",
                "policy_kwargs": dict(net_arch=[256, 256]),
                "use_rms_prop": True,
            },           
        },
    },
}